name: Node.js CI

on:
  push:
    branches: [main, export-static]
  pull_request:
    branches: [main]
  repository_dispatch:
    types: [publish-event]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        env:
            NEXT_PUBLIC_HYGRAPH_ENDPOINT: ${{ secrets.NEXT_PUBLIC_HYGRAPH_ENDPOINT }}
            NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@8a24039354ee91000cb948cb4a1dbdf1a1b94a3c # v4.3.4
        if: |
          (github.event_name == 'push' && github.ref == 'refs/heads/export-static')
        with:
          server: zieloneparafie.atthost24.pl
          username: zieloneparafie_cieplydom_github_action
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/

          